version: '2'
services:
    scandroid-app:
        image: scandroid
        external_links:
            - scandroid-mysql:mysql
        environment:
            - SPRING_PROFILES_ACTIVE=prod
            - SPRING_DATASOURCE_URL=jdbc:mysql://mysql:3306/scandroid?useUnicode=true&characterEncoding=utf8&useSSL=false
        ports:
            - 8080:8080
    scandroid-mysql:
        extends:
            file: mysql.yml
            service: scandroid-mysql
